[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = 'colorscheme molokai'

[[plugins]]
repo = 'kassio/neoterm'
on_cmd = ['TREPLSendSelection', 'TREPLSendLine', 'Tnew']
hook_add = '''
    let g:neoterm_default_mod='vertical'
    let s:mydepth = strchars(getcwd()) - strchars(substitute(getcwd(), "/", "", "g"))
    for i in range(s:mydepth)
        let s:myls = system("ls ." . repeat("/..", i))
        if s:myls =~ 'Pipfile'
            let g:neoterm_repl_python = 'pipenv shell "ipython --no-autoindent || python"'
        endif
    endfor
    let g:neoterm_autoscroll=1
    tnoremap jj <c-\><c-n>
'''
